### ISSUE TITLE
关于修改开源许可

### ISSUE THREAD

**Issue by qyl27** [SinoCraftProject/SinoSeries#2]
现为符合TeaCon参赛要求，需要把华夏丹青（SinoCalligraphy）、华夏飨宴（SinoFeast）、华夏九筮（SinoDivination）的许可证从ARR（保留所有权利）改为CC BY-NC-SA 4.0。

同意请在自己的ID前面打勾。

- [x] @qyl27 
- [x] @luiqn2007 
- [x] @11zi 
- [x] @skyinr 
- [x] @EvanLuo42 
- [x] @theflysong 
- [x] @Timicasto

**Comment by EvanLuo42** [comment]
> 现为符合TeaCon参赛要求，需要把华夏丹青（SinoCalligraphy）、华夏飨宴（SinoFeast）、华夏九筮（SinoDivination）的许可证从ARR（保留所有权利）改为CC BY-NC-SA 4.0。
> 
> 同意请在自己的ID前面打勾。
> 
> * [x]  @qyl27
> * [ ]  @luiqn2007
> * [ ]  @11zi
> * [ ]  @skyinr
> * [x]  @EvanLuo42
> * [ ]  @theflysong
> * [ ]  @Timicasto

**Comment by skyinr** [comment]
> 现为符合TeaCon参赛要求，需要把华夏丹青（SinoCalligraphy）、华夏飨宴（SinoFeast）、华夏九筮（SinoDivination）的许可证从ARR（保留所有权利）改为CC BY-NC-SA 4.0。
 > 同意请在自己的ID前面打勾。
 > 
 > * [x]   @qyl27
 > * [ ]   @luiqn2007
 > * [ ]   @11zi
 > * [x]   @skyinr
 > * [x]   @EvanLuo42
 > * [ ]   @theflysong
 > * [ ]   @Timicasto

**Comment by qyl27** [comment]
诶不是，这个不是让你们接龙的诶，直接点选一楼那个勾就可以的（（（

**Comment by 11zi** [comment]
冗余投票，小子

**Comment by qyl27** [comment]
已通过。
